weather.api.url=http://api.weatherapi.com/v1/current.json
weather.api.key=${WEATHER_API_KEY}
weather.api.location=CABA

alerta.condicion.temperatura.minima=35
alerta.condicion.humedad.minima=60.0

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cdasilvagonzlez@frba.utn.edu.ar
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

alerta.correos.destinos_1=admin@clima.com,emergencias@clima.com,meteorologia@clima.com
alerta.correos.destinos=cdasilvagonzlez@frba.utn.edu.ar